version: "3"
services:
  grafana:
    image: grafana/grafana:8.3.3
    container_name: grafana
    ports:
      - "3000:3000"
  influxdb:
    image: influxdb:2.1.1
    container_name: influxdb
    ports:
      - "8086:8086"
      - "8088:8088"
    environment:
      - DOCKER_INFLUXDB_INIT_USERNAME=root
      - DOCKER_INFLUXDB_INIT_PASSWORD=root
      - DOCKER_INFLUXDB_INIT_ORG=testRetention
      - DOCKER_INFLUXDB_INIT_BUCKET=testSeries