{
 "title": "DataCo SMART SUPPLY CHAIN FOR BIG DATA ANALYSIS",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Benefit Per Order",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Average",
     "measurement": "http://example.com/supplychain/supplychain/Benefit per order",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Maximum",
     "measurement": "http://example.com/supplychain/supplychain/Benefit per order",
     "select": [
      [
       { "params": [ "Maximum" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Median",
     "measurement": "http://example.com/supplychain/supplychain/Benefit per order",
     "select": [
      [
       { "params": [ "Median" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Minimum",
     "measurement": "http://example.com/supplychain/supplychain/Benefit per order",
     "select": [
      [
       { "params": [ "Minimum" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Benefit per Order - Cardinalities",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "% Null Values",
     "measurement": "http://example.com/supplychain/supplychain/Benefit per order",
     "select": [
      [
       { "params": [ "% Null Values" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "% Uniqueness",
     "measurement": "http://example.com/supplychain/supplychain/Benefit per order",
     "select": [
      [
       { "params": [ "Uniqueness" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Size",
     "measurement": "http://example.com/supplychain/supplychain/Benefit per order",
     "select": [
      [
       { "params": [ "Size" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "# Decimals",
     "measurement": "http://example.com/supplychain/supplychain/Benefit per order",
     "select": [
      [
       { "params": [ "Decimals" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Order Item Discount Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Average",
     "measurement": "http://example.com/supplychain/supplychain/Order Item Discount Rate",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Maximum",
     "measurement": "http://example.com/supplychain/supplychain/Order Item Discount Rate",
     "select": [
      [
       { "params": [ "Maximum" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Median",
     "measurement": "http://example.com/supplychain/supplychain/Order Item Discount Rate",
     "select": [
      [
       { "params": [ "Median" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Minimum",
     "measurement": "http://example.com/supplychain/supplychain/Order Item Discount Rate",
     "select": [
      [
       { "params": [ "Minimum" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Order Item Discount Rate - Cardinalities",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "% Null Values",
     "measurement": "http://example.com/supplychain/supplychain/Order Item Discount Rate",
     "select": [
      [
       { "params": [ "% Null Values" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "% Uniqueness",
     "measurement": "http://example.com/supplychain/supplychain/Order Item Discount Rate",
     "select": [
      [
       { "params": [ "Uniqueness" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "# Decimals",
     "measurement": "http://example.com/supplychain/supplychain/Order Item Discount Rate",
     "select": [
      [
       { "params": [ "Decimals" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Size",
     "measurement": "http://example.com/supplychain/supplychain/Order Item Discount Rate",
     "select": [
      [
       { "params": [ "Size" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Order Item Total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Average",
     "measurement": "http://example.com/supplychain/supplychain/Order Item Total",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Maximum",
     "measurement": "http://example.com/supplychain/supplychain/Order Item Total",
     "select": [
      [
       { "params": [ "Maximum" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Median",
     "measurement": "http://example.com/supplychain/supplychain/Order Item Total",
     "select": [
      [
       { "params": [ "Median" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Minimum",
     "measurement": "http://example.com/supplychain/supplychain/Order Item Total",
     "select": [
      [
       { "params": [ "Minimum" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Order Zipcode Cardinalities",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "% Null Values",
     "measurement": "http://example.com/supplychain/supplychain/Order Zipcode",
     "select": [
      [
       { "params": [ "% Null Values" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "% Uniqueness",
     "measurement": "http://example.com/supplychain/supplychain/Order Zipcode",
     "select": [
      [
       { "params": [ "Uniqueness" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Size",
     "measurement": "http://example.com/supplychain/supplychain/Order Zipcode",
     "select": [
      [
       { "params": [ "Size" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "# Decimals",
     "measurement": "http://example.com/supplychain/supplychain/Order Zipcode",
     "select": [
      [
       { "params": [ "Decimals" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Order Profit Per Order",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Average",
     "measurement": "http://example.com/supplychain/supplychain/Order Profit Per Order",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Maximum",
     "measurement": "http://example.com/supplychain/supplychain/Order Profit Per Order",
     "select": [
      [
       { "params": [ "Maximum" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Median",
     "measurement": "http://example.com/supplychain/supplychain/Order Profit Per Order",
     "select": [
      [
       { "params": [ "Median" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Minimum",
     "measurement": "http://example.com/supplychain/supplychain/Order Profit Per Order",
     "select": [
      [
       { "params": [ "Minimum" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Order Item Product Price",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Average",
     "measurement": "http://example.com/supplychain/supplychain/Order Item Product Price",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Maximum",
     "measurement": "http://example.com/supplychain/supplychain/Order Item Product Price",
     "select": [
      [
       { "params": [ "Maximum" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Median",
     "measurement": "http://example.com/supplychain/supplychain/Order Item Product Price",
     "select": [
      [
       { "params": [ "Median" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Minimum",
     "measurement": "http://example.com/supplychain/supplychain/Order Item Product Price",
     "select": [
      [
       { "params": [ "Minimum" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}