name: Java CI with Maven

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: [ self-hosted ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.4
        with:
          maven-version: 3.8.2
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: maven
      - name: Build with Maven
        run: mvn -B package -DskipTests
      - uses: actions/upload-artifact@v3
        with:
          name: target
          path: target
  test:
    runs-on: [ self-hosted ]
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.4
        with:
          maven-version: 3.8.2
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: maven
      - uses: actions/download-artifact@v3
        with:
          name: target
          path: target/
      - name: Test with Maven
        run: mvn -B test --fail-at-end
      - uses: actions/upload-artifact@v3
        if: ${{ always() }} # Always upload the test results, even if they fail
        with:
          name: test-results
          path: target/surefire-reports
